### ISSUE TITLE
Delete 'deleted' tasks?

### ISSUE THREAD

**Issue by fredgolightly** [Google-Tasks-Backup/tasks-backup#28]
Hi
I've 100s of deleted tasks which list themselves as either '<Unnamed Task>
- Deleted -' or the actual task if it's not been wiped before deleting.

Is there any way to actually clear all these so there's no entry for the deleted items, as if they are, in fact, actually deleted?

**Comment by Google-Tasks-Backup** [comment]
Hi Fred,

This issue is outside the scope of GTB.

When a user deletes a task, the task's 'deleted' flag is set. The actual deletion is done at some indeterminate time by the Google Tasks server. I have not been able to find any documentation indicating how long it takes.

I have 'deleted' tasks in my account dating back to June, so it seems that Google deletes tasks ~3 months after they are marked as deleted.

Regards,

Julie Smith
GBT/GTI Developer
